name: PyPi Release

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: macos-latest
            target: x86_64
            args: "--release --sdist"
          - os: macos-latest
            target: universal2-apple-darwin
            args: "--release"
          - os: macos-latest
            target: x64
            args: "--release"
          - os: macos-latest
            target: x86
            args: "--release"
          - os: macos-latest
            target: x86_64
            args: "--release"
          - os: macos-latest
            target: i686
            args: "--release"
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Build wheels for ${{ matrix.platform.os }}-${{ matrix.platform.target }}
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: ${{ matrix.platform.args }}

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheel-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: target/wheels/*.whl

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: wheel-artifacts

      - name: Copy all wheel files into dist/
        run: |
          mkdir dist
          find wheel-artifacts -name '*.whl' -exec cp -prv '{}' 'dist/' ';'

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
